---
# tasks file for ansible-role-smartgit


- fail: msg="The SmartGit role currently only supports Linux+apt or Mac OS X."
  when: ansible_pkg_mgr != 'apt' and ansible_distribution !='MacOSX' and ansible_os_family != "RedHat"


- include: setup-deb.yml
  sudo: Yes
  when: ansible_pkg_mgr == 'apt'

  
- include: setup-dmg.yml
  sudo: Yes
  when: ansible_distribution == 'MacOSX'

- import_tasks: setup-targz.yml
  when:
    - ansible_os_family == "RedHat"
